<a href="https://colab.research.google.com/github/Teja1deep/PESU_io_assignments/blob/main/Machine_learning_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd

In [3]:
dataset = pd.read_csv('/content/PESUIODATABASE.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [4]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [5]:
y

array([0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1,
       1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1])

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [7]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [8]:
X_train

array([[-0.67932793,  0.5824378 ],
       [ 0.18541728,  0.60140209],
       [ 1.72307172,  1.99496182],
       [-0.31296075,  1.21426495],
       [ 0.75400333, -0.82755765],
       [-1.05887971, -0.7324201 ],
       [-1.03069762, -0.6688897 ],
       [ 1.03681308, -0.59271645],
       [-0.97054287, -0.66288434],
       [-0.84001529,  2.18049586],
       [ 0.3342385 ,  0.66524856],
       [-0.32911189,  0.64533605],
       [ 1.63209795,  1.5865973 ],
       [-1.07783258, -0.38821812],
       [ 0.85453593, -0.62874861],
       [-0.39206837, -0.63412183],
       [-0.85863854,  0.25720011],
       [ 1.11740397, -0.56806286],
       [-0.88533736, -0.82439694],
       [-0.48155887,  2.20799409],
       [ 0.51420834, -0.84178088],
       [-0.42255777,  2.21557981],
       [ 0.46822704, -0.81048979],
       [-0.24670811, -0.82123622],
       [ 0.63204574, -0.56079321],
       [-0.43755525,  1.35649717],
       [-0.10629208, -0.56490215],
       [-1.09266526, -0.83988445],
       [-1.0455303 ,

In [ ]:
X_test

array([[-1.08112873, -0.44858779],
       [ 1.31121765, -0.81744336],
       [-0.14238493,  0.95129337],
       [-0.2966448 , -0.811438  ],
       [ 1.5131069 , -0.56521822],
       [ 1.66225773,  1.22722388],
       [-1.10898121,  0.25309118],
       [ 0.68033435, -0.82439694],
       [-1.09744468, -0.69417543],
       [ 0.82915557, -0.55510393],
       [-0.79057302, -0.76118261],
       [ 0.20618303, -0.62811647],
       [ 1.60210297,  0.92885228],
       [ 0.8800811 , -0.55605214],
       [-0.5651163 , -0.82376479],
       [-1.10650909, -0.82502908],
       [-1.01438167, -0.73210403],
       [ 0.3124839 ,  0.95255765],
       [-0.99031977,  0.89060762],
       [-0.64274065, -0.57217179],
       [ 1.69258232,  1.99432968],
       [ 0.65610764, -0.60030217],
       [-0.93428521, -0.7324201 ],
       [ 1.01027907, -0.55510393],
       [-0.80079109,  0.31124836],
       [ 0.16481634, -0.69512365],
       [ 1.57227281,  1.93490822],
       [ 1.75372592, -0.81775943],
       [ 0.1443802 ,

In [9]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, y_train)

LogisticRegression(random_state=0)

In [10]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]]


In [11]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[31  0]
 [ 2 17]]


0.96